fixed auto python3 installation

diff --git a/dump b/dump
--- a/dump
+++ b/dump
@@ -1,38 +1,29 @@
 #!/usr/bin/env bash
 
+set -e
+
 SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 
 PYTHON_REQUIRED_MAJOR="3"
 PYTHON_REQUIRED_MINOR="7"
-PYTHON_ACTUAL_MAJOR=`python3 -c 'import sys; print(sys.version_info[0])'`
-PYTHON_ACTUAL_MINOR=`python3 -c 'import sys; print(sys.version_info[1])'`
 
-
-validateLastCommand() {
-    if [[ "$!" != "0" ]]; then
-        exit 1
-    fi
-}
-
-if [[ "$PYTHON_REQUIRED_MAJOR" != "$PYTHON_ACTUAL_MAJOR" ]]; then
+if command -v python3 &>/dev/null; then
+    echo "Python $PYTHON_REQUIRED_MAJOR.x found.."
+else
     echo "Oh shit.. Python $PYTHON_REQUIRED_MAJOR.x is required to run this program.."
 
     echo "Trying to install the latest Python $PYTHON_REQUIRED_MAJOR version.."
     brew install python3
-
-    validateLastCommand
 fi
+
+PYTHON_ACTUAL_MAJOR=`python3 -c 'import sys; print(sys.version_info[0])'`
+PYTHON_ACTUAL_MINOR=`python3 -c 'import sys; print(sys.version_info[1])'`
 
 if [[ "$PYTHON_REQUIRED_MINOR" > "$PYTHON_ACTUAL_MINOR" ]]; then
     echo "Trying to update Python $PYTHON_REQUIRED_MAJOR to the latest version.."
 
     brew upgrade python3
-
-    validateLastCommand
 fi
 
 
-
 PYTHONPATH=${SCRIPT_DIR}/pkg python3 envdump.py $@
-
-validateLastCommand
