validating python version before executing python

diff --git a/envdump b/envdump
--- a/envdump
+++ b/envdump
@@ -1,3 +1,12 @@
 #!/usr/bin/env bash
 
+PYTHON_REQUIRED_MAJOR="2"
+PYTHON_ACTUAL_MAJOR=`python -c 'import sys; print sys.version_info[0]'`
+
+if [[ "$PYTHON_REQUIRED_MAJOR" != "$PYTHON_ACTUAL_MAJOR" ]]; then
+    echo "Oh shit.. Python $PYTHON_REQUIRED_MAJOR.x is required to run this program.."
+
+    exit 1
+fi
+
 python inspector/dump.py
